//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubMng.DAtaLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class athlete
    {
        public int athlete_Id { get; set; }
        public string fullName { get; set; }
        public string nID { get; set; }
        public string phoneNumber { get; set; }
        public string adresss { get; set; }
        public string lastpay { get; set; }
        public string status { get; set; }
        public Nullable<int> expired { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> tempmydate { get; set; }
        public string mydate { get; set; }
        public string plantext { get; set; }
        public string itemplans { get; set; }
    }
}
