//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubMng.DAtaLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_listitem
    {
        public int id { get; set; }
        public string name { get; set; }
    }
}
